### ISSUE TITLE
hex.pm published version doesn't match latest main

### ISSUE THREAD

**Issue by jfburdet** [Cantido/exglicko2#1]
A title explained, it seems that latest main doesn't match what is published on hex.pm

Is there a reason ? Do you need help/pr for that ?

**Comment by Cantido** [comment]
Usually I like to build up a good batch of changes before I push to hex, and this time around I completely forgot to push it. I'll do that tonight. Thank you for reminding me!

**Comment by Cantido** [comment]
Just pushed!

Are you using this library? I didn't know anyone was. I can clean things up over the coming weeks. This was a fun little project, but I didn't put in the work to make this nice to use, so I'm sorry if it's rough around the edges.

**Comment by jfburdet** [comment]
> Are you using this library?  [...] so I'm sorry if it's rough around the edges.

Yes I'm planning to use in a tournament management application i'm writing. 

I looked at both glicko found on hex.pm and found your code more readable : thanks for having written it.

Cheers,
